apiVersion: v1
kind: ConfigMap
metadata:
  name: setu-rag-config
  namespace: setu-rag
data:
  LLM_PROVIDER: "groq"
  LLM_MODEL: "llama-3.1-8b"
  EMBEDDINGS_PROVIDER: "jina"
  EMBEDDINGS_MODEL: "jina-embeddings-v2-base-en"
